<?php

return [
    /*
    |--------------------------------------------------------------------------
    | Laravel API Starter Configuration
    |--------------------------------------------------------------------------
    |
    | This file contains the configuration options for the Laravel API Starter
    | package. You can customize namespaces, API versioning, and other options
    | to match your project's requirements.
    |
    */

    /*
    |--------------------------------------------------------------------------
    | Namespaces
    |--------------------------------------------------------------------------
    |
    | Customize the namespaces for generated classes. This allows you to
    | organize your code according to your project's structure.
    |
    */

    'model_namespace' => 'App\\Models',
    'controller_namespace' => 'App\\Http\\Controllers\\Api',
    'request_namespace' => 'App\\Http\\Requests',
    'resource_namespace' => 'App\\Http\\Resources',
    'service_namespace' => 'App\\Services',

    /*
    |--------------------------------------------------------------------------
    | API Versioning
    |--------------------------------------------------------------------------
    |
    | Configure API versioning for your application. When enabled, controllers
    | and routes will be generated with version prefixes.
    |
    */

    'api_versioning' => [
        'enabled' => false,
        'default_version' => 'v1',
        'prefix' => 'api',
    ],

    /*
    |--------------------------------------------------------------------------
    | Database Configuration
    |--------------------------------------------------------------------------
    |
    | Configure database-related options for generated components.
    |
    */

    'database' => [
        'soft_deletes' => true,
        'timestamps' => true,
        'uuid_primary_key' => false,
    ],

    /*
    |--------------------------------------------------------------------------
    | Generated Components
    |--------------------------------------------------------------------------
    |
    | Configure which components should be generated by default when using
    | the api:starter command without specific options.
    |
    */

    'default_components' => [
        'model' => true,
        'migration' => true,
        'controller' => true,
        'request' => true,
        'resource' => true,
        'service' => true,
        'seeder' => true,
        'routes' => false,
    ],

    /*
    |--------------------------------------------------------------------------
    | Authentication
    |--------------------------------------------------------------------------
    |
    | Configure authentication options for generated controllers.
    |
    */

    'authentication' => [
        'enabled' => true,
        'middleware' => ['auth:sanctum'],
    ],

    /*
    |--------------------------------------------------------------------------
    | Validation
    |--------------------------------------------------------------------------
    |
    | Configure default validation rules and options.
    |
    */

    'validation' => [
        'authorize_by_default' => true,
        'include_update_rules' => true,
    ],

    /*
    |--------------------------------------------------------------------------
    | Resource Transformations
    |--------------------------------------------------------------------------
    |
    | Configure how API resources should transform data by default.
    |
    */

    'resources' => [
        'include_timestamps' => true,
        'include_relationships' => true,
        'wrap_response' => false,
    ],

    /*
    |--------------------------------------------------------------------------
    | Service Layer
    |--------------------------------------------------------------------------
    |
    | Configure service layer options for business logic abstraction.
    |
    */

    'services' => [
        'include_caching' => false,
        'include_events' => true,
        'include_validation' => true,
    ],

    /*
    |--------------------------------------------------------------------------
    | Stub Customization
    |--------------------------------------------------------------------------
    |
    | Configure stub template options for generated files.
    |
    */

    'stubs' => [
        'include_docblocks' => true,
        'include_type_hints' => true,
        'php_version' => '8.1',
    ],
];